name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Primeiro step do fluxo
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: data da execução
        run: echo "14/09/2026"
